report_type: "incremental"

platforms:
  - id: "toutiao"
    name: "今日头条"
  - id: "baidu"
    name: "百度热搜"
  - id: "zhihu"
    name: "知乎热榜"
  - id: "weibo"
    name: "微博热搜"
  - id: "bilibili"
    name: "哔哩哔哩"
  - id: "douyin"
    name: "抖音热点"
  - id: "wallstreetcn-hot"
    name: "华尔街见闻"
  - id: "thepaper"
    name: "澎湃新闻"
  - id: "cls"
    name: "财联社"
  - id: "weread"
    name: "微信读书"
  - id: "sspai"
    name: "少数派"

push_window:
  enabled: true
  weekday_morning_start: 9
  weekday_morning_end: 18
  weekday_evening_start: 20
  weekday_evening_end: 22
  weekend_start: 10
  weekend_end: 22

weight:
  rank_weight: 0.5
  frequency_weight: 0.4
  hotness_weight: 0.1

output:
  enable_html: true
  enable_txt: false
  save_to_github_pages: false

min_score_threshold: 1.0
max_titles_per_report: 30
custom_title_prefix: "【汽车监测】"
